# Generated by Django 3.1.2 on 2020-11-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPaginas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='InvocadorU',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
